[package]
name = "zapret-ux"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
camino = "1.2.2"
clap = { version = "4.5.53", features = ["derive"] }
